name: objectbox_generator
version: 0.6.4
repository: https://github.com/objectbox/objectbox-dart
homepage: https://objectbox.io
description: ObjectBox binding code generator - finds annotated entities and adds them to the ObjectBox DB model.

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  objectbox:
    git:
      url: git@github.com:lzhAndroid/objectbox-dart.git
      ref: fa40ae5b596b126ce3acd8ca18199f0fc63e973e
  build: ^1.0.0
  source_gen: ^0.9.0
  analyzer: ">=0.35.0 <0.100.0"
  glob: ^1.1.0
  path: ^1.6.0
  dart_style: ^1.3.0

# NOTE: remove before publishing
dependency_overrides:
  objectbox:
    path: ..