name: objectbox
version: 0.3.0
description: >-
  ObjectBox binding for Dart.
environment:
  sdk: '>=2.6.0-dev'
dependencies:
  # take care updating flatbuffers - keep aligned with other bindings
  flat_buffers: 1.11.0
  ffi: ">=0.1.3-dev"
dev_dependencies:
  build_runner: ^1.0.0
  objectbox_model_generator:
    path: generator
  pedantic: ^1.8.0+1
  test: ^1.0.0
