name: objectbox_demo
description: An example project for the objectbox-dart binding.
version: 0.3.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider: any
  intl: any
  objectbox: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  objectbox_generator: ^0.5.0

flutter:
  uses-material-design: true

# ---------------------------------
dependency_overrides:
  objectbox:
    path: ../../..
  objectbox_generator:
    path: ../../../generator