name: objectbox_generator_test

dependencies:
  objectbox: any

dev_dependencies:
  objectbox_generator: any
  test: ^1.0.0
  build_runner: ^1.0.0
  build_test: ^0.10.10
  io: any
  path: any

dependency_overrides:
  objectbox:
    path: ../../../
  objectbox_generator:
    path: ../../