name: Dart CI

on: [push, pull_request]

jobs:
  generator:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        working-directory: generator
        run: pub get
# Disabled temporarily, pending rework in #37
#      - name: Run tests
#        working-directory: generator
#        run: pub run test

  lib:
    needs: generator
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ObjectBox C-API
        run: ./install.sh
      - name: Install dependencies
        run: pub get
      - name: Generate ObjectBox models
        run: pub run build_runner build
      - name: Run tests
        run: pub run test
